Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

src = ['CM3/DeviceSupport/NXP/LPC17xx/system_LPC17xx.c']

src += Split("""
LPC17xx/src/lpc17xx_adc.c
LPC17xx/src/lpc17xx_can.c
LPC17xx/src/lpc17xx_dac.c
LPC17xx/src/lpc17xx_gpio.c
LPC17xx/src/lpc17xx_i2c.c
LPC17xx/src/lpc17xx_i2s.c
LPC17xx/src/lpc17xx_nvic.c
LPC17xx/src/lpc17xx_pinsel.c
LPC17xx/src/lpc17xx_pwm.c
LPC17xx/src/lpc17xx_rtc.c
LPC17xx/src/lpc17xx_spi.c
LPC17xx/src/lpc17xx_systick.c
LPC17xx/src/lpc17xx_timer.c
LPC17xx/src/lpc17xx_uart.c
LPC17xx/src/lpc17xx_wdt.c
""")

# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
    src += ['CM3/DeviceSupport/NXP/LPC17xx/startup/gcc/startup_LPC17xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += ['CM3/DeviceSupport/NXP/LPC17xx/startup/arm/startup_LPC17xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += ['CM3/DeviceSupport/NXP/LPC17xx/startup/iar/startup_LPC17xx.s']

CPPPATH = [cwd + '/CM3/DeviceSupport/NXP/LPC17xx/', cwd + '/CMSIS/Include', cwd + '/LPC17xx/inc/']

if GetDepend(['RT_USING_BSP_CMSIS']):
    CPPPATH += [cwd + '/CM3/CoreSupport']
    src += ['CM3/CoreSupport/core_cm3.c']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
