from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
led.c
""")

if GetDepend(['BSP_USING_SERIAL']):
    src += ['drv_uart.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
