from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
led.c
""")

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_uart.c']

if GetDepend(['RT_USING_PIN']):
    src += ['drv_pin.c']

if GetDepend(['RT_USING_I2C']):
    src += ['drv_i2c.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
